import type { FeedItem } from "./types";

export const demoItems: FeedItem[] = [
  {
    id: "demo-openxr",
    title: "OpenXR moves spatial apps toward a shared foundation",
    url: "https://www.khronos.org/openxr/",
    source: "Khronos Group",
    sourceUrl: "https://www.khronos.org/",
    publishedAt: "2026-08-11T07:30:00.000Z",
    summary: "The standards layer remains one of the strongest signals for where interoperable XR hardware and software are heading.",
    kind: "article",
    topics: ["Industry", "VR", "AR"],
    relevance: 96,
    readingMinutes: 6,
    featured: true,
  },
  {
    id: "demo-optics",
    title: "Why lighter optics are the next hardware battleground",
    url: "https://www.roadtovr.com/",
    source: "Road to VR",
    sourceUrl: "https://www.roadtovr.com/",
    publishedAt: "2026-08-11T05:10:00.000Z",
    summary: "Display efficiency, field of view, and all-day comfort are converging into a single design problem for the next headset cycle.",
    kind: "article",
    topics: ["Hardware", "VR"],
    relevance: 92,
    readingMinutes: 5,
  },
  {
    id: "demo-agents",
    title: "Spatial interfaces are becoming a home for embodied AI",
    url: "https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API",
    source: "XR Research Watch",
    sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API",
    publishedAt: "2026-08-10T18:45:00.000Z",
    summary: "Multimodal models can now interpret rooms, objects, gestures, and intent—changing what an XR interface can reasonably understand.",
    kind: "research",
    topics: ["AI + XR", "AR"],
    relevance: 89,
    readingMinutes: 8,
  },
  {
    id: "demo-enterprise",
    title: "Enterprise XR shifts from pilots to measurable workflows",
    url: "https://www.uploadvr.com/",
    source: "UploadVR",
    sourceUrl: "https://www.uploadvr.com/",
    publishedAt: "2026-08-10T14:20:00.000Z",
    summary: "Training, remote assistance, and spatial design are increasingly evaluated on time saved rather than novelty.",
    kind: "article",
    topics: ["Industry", "MR"],
    relevance: 84,
    readingMinutes: 4,
  },
  {
    id: "demo-video",
    title: "A practical tour of today’s WebXR stack",
    url: "https://www.youtube.com/results?search_query=WebXR+2026",
    source: "YouTube XR",
    sourceUrl: "https://www.youtube.com/",
    publishedAt: "2026-08-09T16:00:00.000Z",
    summary: "A developer-focused overview of browsers, runtimes, input systems, and deployment options for immersive web experiences.",
    kind: "video",
    topics: ["VR", "AR"],
    relevance: 80,
  },
  {
    id: "demo-presence",
    title: "Presence is becoming a product metric, not just a research term",
    url: "https://arxiv.org/search/?query=virtual+reality+presence&searchtype=all",
    source: "Research Signal",
    sourceUrl: "https://arxiv.org/",
    publishedAt: "2026-08-08T11:15:00.000Z",
    summary: "Teams are connecting latency, embodiment, comfort, and interaction quality to outcomes they can test and compare.",
    kind: "research",
    topics: ["VR", "Industry"],
    relevance: 76,
    readingMinutes: 7,
  },
];

