import type { SourceDefinition } from "./types";

export const sources: SourceDefinition[] = [
  {
    id: "road-to-vr",
    name: "Road to VR",
    homepage: "https://www.roadtovr.com/",
    type: "rss",
    feedUrl: "https://www.roadtovr.com/feed/",
    enabled: true,
  },
  {
    id: "uploadvr",
    name: "UploadVR",
    homepage: "https://www.uploadvr.com/",
    type: "rss",
    feedUrl: "https://www.uploadvr.com/rss/",
    enabled: true,
  },
  {
    id: "the-xr-beat",
    name: "The XR Beat",
    homepage: "https://thexrbeat.com/",
    type: "rss",
    feedUrl: "https://thexrbeat.com/feed/",
    enabled: true,
  },
  {
    id: "youtube-mrtv-rss",
    name: "MRTV",
    homepage: "https://www.youtube.com/@mixedrealityTV",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC2mgZjuHRDW02mx_ok4wfPw",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
  {
    id: "youtube-thrillseeker-rss",
    name: "ThrillSeeker",
    homepage: "https://www.youtube.com/@ThrillSeekerVR",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSbdMXOI_3HGiFviLZO6kNA",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
  {
    id: "youtube-beardo-benjo-rss",
    name: "Beardo Benjo",
    homepage: "https://www.youtube.com/@BeardoBenjo",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSzUG-hFZgaKpYA6w2WS8sQ",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
  {
    id: "youtube-meta-developers-rss",
    name: "Meta Developers",
    homepage: "https://www.youtube.com/@MetaDevelopers",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCP_lo1MFyx5IXDeD9s_6nUw",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
  {
    id: "youtube-firedragon-rss",
    name: "FireDragon Game Studio",
    homepage: "https://www.youtube.com/@firedragongamestudio",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQ33xRqfVWKx4GBRVAh3YGQ",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
  {
    id: "youtube-cas-chary-rss",
    name: "Cas & Chary",
    homepage: "https://www.youtube.com/@CasandChary",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCN0FGqUt7e79xKoPAZQ8tww",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
  {
    id: "youtube-awe-xr-rss",
    name: "AWE XR",
    homepage: "https://www.youtube.com/@AWEXR",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCutPI2lji_hFToXec7qOCFA",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
  {
    id: "youtube-varjo-rss",
    name: "Varjo",
    homepage: "https://www.youtube.com/@varjodotcom",
    type: "rss",
    feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCt1LdZcAiVK7iaiKVsy39Sg",
    kind: "video",
    itemLimit: 5,
    enabled: true,
  },
];
